name: Test
run-name: ${{ github.actor }} is testing out GitHub Actions
on:
  push:
    branches:
      - main
      - master
  pull_request:
  schedule:
      - cron: '0 22 * * *'
env:
  VERSIONS_LOCATION: "examples/resources/versions/"
jobs:
  checkForNewVersion:
    runs-on: ubuntu-latest
    permissions: read-all

    outputs:
      isInRepo: ${{ steps.save-var.outputs.IS_IN_REPO }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Check for latest
        id: save-var
        run: |
          LATEST=$(curl -sSL "https://piston-meta.mojang.com/mc/game/version_manifest.json" | jq -cr '.latest.release')
          if [[ -e ${{ env.VERSIONS_LOCATION }}"$LATEST" ]]; then echo "IS_IN_REPO=TRUE" >> $GITHUB_OUTPUT; else echo "IS_IN_REPO=FALSE" >> $GITHUB_OUTPUT; fi
      - name: Is latest in repo?
        run: echo "${{ steps.save-var.outputs.IS_IN_REPO }}"

  createWorld:
    runs-on: ubuntu-latest
    needs:
      - checkForNewVersion
    permissions: write-all
    if: ${{ needs.checkForNewVersion.outputs.isInRepo == 'FALSE' }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Get latest version
        run: |
          echo "LATEST=$(curl -sSL "https://piston-meta.mojang.com/mc/game/version_manifest.json" |
          jq -cr '.latest.release')" >> $GITHUB_ENV

      - name: Get last version
        run: echo "LAST_VERSION=$(curl -sSL "https://piston-meta.mojang.com/mc/game/version_manifest.json" | jq -cr '[.versions[] | select(.type == "release")] [1] .id')" >> $GITHUB_ENV

      - name: Delete latest version folder
        run: rm -r ${{ env.VERSIONS_LOCATION }}latest

      - name: Copy last version into latest folder
        run: cp -R ${{ env.VERSIONS_LOCATION }}${{ env.LAST_VERSION }} ${{ env.VERSIONS_LOCATION }}latest

      - name: Start server
        run: docker run --ip 172.17.0.2 --name mc -e EULA=TRUE -e UID="$(id -u)" -e ENABLE_AUTOSTOP=TRUE -e AUTOSTOP_TIMEOUT_INIT=5 -e MEMORY=8G -v "$GITHUB_WORKSPACE"/${{ env.VERSIONS_LOCATION }}latest itzg/minecraft-server:latest --forceUpgrade

      - name: Copy upgraded world into version folder
        run: cp -R ${{ env.VERSIONS_LOCATION }}latest ${{ env.VERSIONS_LOCATION }}${{ env.LATEST }}

      - name: Show resource folder
        run: tree ${{ env.VERSIONS_LOCATION }}

      - uses: EndBug/add-and-commit@v9
        with:
          add: ./${{ env.VERSIONS_LOCATION }}${{ env.LATEST }}/* ./${{ env.VERSIONS_LOCATION }}latest/*
          message: 'add latest Minecraft world'
          push: true

  tests:
    runs-on: ubuntu-latest
    needs:
      - createWorld

    strategy:
      matrix:
        php-version: [ '8.0', '8.1', '8.2' ]

    name: Run tests on PHP v${{ matrix.php-version }}

    if: always()

    steps:

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}

      - name: Set composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Restore composer from cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Update composer
        run: composer update

      - name: Install composer dependencies
        run: composer install --no-interaction --prefer-dist --no-progress

      - name: Run phpunit tests
        run: vendor/bin/phpunit --colors=always --testdox
